name: 'Create Release'

on:
  push:
    tags:
      - 'v[1-9].[0-9]+.0'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4